#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : R-repr
Version  : 1.1.7
Release  : 81
URL      : https://cran.r-project.org/src/contrib/repr_1.1.7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/repr_1.1.7.tar.gz
Summary  : Serializable Representations
Group    : Development/Tools
License  : GPL-3.0
Requires: R-base64enc
Requires: R-htmltools
Requires: R-jsonlite
Requires: R-pillar
BuildRequires : R-base64enc
BuildRequires : R-htmltools
BuildRequires : R-jsonlite
BuildRequires : R-pillar
BuildRequires : buildreq-R

%description
mime types.

%prep
%setup -q -n repr
pushd ..
cp -a repr buildavx2
popd
pushd ..
cp -a repr buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711242412

%install
export SOURCE_DATE_EPOCH=1711242412
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/repr/DESCRIPTION
/usr/lib64/R/library/repr/INDEX
/usr/lib64/R/library/repr/Meta/Rd.rds
/usr/lib64/R/library/repr/Meta/features.rds
/usr/lib64/R/library/repr/Meta/hsearch.rds
/usr/lib64/R/library/repr/Meta/links.rds
/usr/lib64/R/library/repr/Meta/nsInfo.rds
/usr/lib64/R/library/repr/Meta/package.rds
/usr/lib64/R/library/repr/NAMESPACE
/usr/lib64/R/library/repr/NEWS.md
/usr/lib64/R/library/repr/R/repr
/usr/lib64/R/library/repr/R/repr.rdb
/usr/lib64/R/library/repr/R/repr.rdx
/usr/lib64/R/library/repr/help/AnIndex
/usr/lib64/R/library/repr/help/aliases.rds
/usr/lib64/R/library/repr/help/paths.rds
/usr/lib64/R/library/repr/help/repr.rdb
/usr/lib64/R/library/repr/help/repr.rdx
/usr/lib64/R/library/repr/html/00Index.html
/usr/lib64/R/library/repr/html/R.css
/usr/lib64/R/library/repr/tests/testthat.R
/usr/lib64/R/library/repr/tests/testthat/helper-stringr.R
/usr/lib64/R/library/repr/tests/testthat/test_array_manipulation.r
/usr/lib64/R/library/repr/tests/testthat/test_escaping.r
/usr/lib64/R/library/repr/tests/testthat/test_repr_array_df.r
/usr/lib64/R/library/repr/tests/testthat/test_repr_htmlwidget.r
/usr/lib64/R/library/repr/tests/testthat/test_repr_list.r
/usr/lib64/R/library/repr/tests/testthat/test_repr_packageIQR.r
/usr/lib64/R/library/repr/tests/testthat/test_repr_ts.r
/usr/lib64/R/library/repr/tests/testthat/test_repr_vector.r
/usr/lib64/R/library/repr/tests/testthat/test_utils.r
